export enum RepoId {
  PR_ATLAS = 'pr-atlas',
  EXTERNAL_EVIDENCE = 'external-evidence',
  SHOPPING_PWA = 'shopping-pwa',
  SHARED_UI_WEB = 'shared-ui-web',
  EGDS_COMPONENTS_REACT = 'egds-components-react',
  PRODUCT_DETAILS_API = 'product-details-experience-api',
  EXP_API_LODGING_OFFERS = 'experience-api-lodging-offers',
  EXP_API_LODGING_SEARCH = 'experience-api-lodging-search',
  EXP_API_LODGING_REVIEWS = 'experience-api-lodging-reviews',
  EXP_API_LODGING_PROPERTY = 'experience-api-lodging-property',
  SHARED_GRAPHQL = 'shared-graphql',
}

export enum ParentFeature {
  SORT_AND_FILTER = 'Sort and Filter',
  AI_SEARCH = 'AI Search',
  LOVED_BY_GUESTS = 'Loved By Guests',
  CAROUSEL = 'Carousel',
  TYPEAHEAD = 'Typeahead',
  GREAT_FIND = 'Great Find',
  SIGNALS = 'Signals',
  ABOUT_THE_HOST = 'About The Host',
  INQUIRY = 'Inquiry',
}

export enum PullRequestId {
  PR_ATLAS = 'pr-atlas',
  PROCESS_EVIDENCE = 'process-evidence',

  // shopping-pwa
  SHOPPING_PWA_17433 = 'shopping-pwa-17433',
  SHOPPING_PWA_17074 = 'shopping-pwa-17074',
  SHOPPING_PWA_15411 = 'shopping-pwa-15411',
  SHOPPING_PWA_15079 = 'shopping-pwa-15079',
  SHOPPING_PWA_15012 = 'shopping-pwa-15012',
  SHOPPING_PWA_14925 = 'shopping-pwa-14925',
  SHOPPING_PWA_14816 = 'shopping-pwa-14816',
  SHOPPING_PWA_14732 = 'shopping-pwa-14732',
  SHOPPING_PWA_13017 = 'shopping-pwa-13017',
  SHOPPING_PWA_12834 = 'shopping-pwa-12834',
  SHOPPING_PWA_12257 = 'shopping-pwa-12257',
  SHOPPING_PWA_11779 = 'shopping-pwa-11779',
  SHOPPING_PWA_8704 = 'shopping-pwa-8704',
  SHOPPING_PWA_8403 = 'shopping-pwa-8403',

  // shared-ui-web
  SHARED_UI_WEB_37156 = 'shared-ui-web-37156',
  SHARED_UI_WEB_36900 = 'shared-ui-web-36900',
  SHARED_UI_WEB_35481 = 'shared-ui-web-35481',
  SHARED_UI_WEB_35318 = 'shared-ui-web-35318',
  SHARED_UI_WEB_35144 = 'shared-ui-web-35144',
  SHARED_UI_WEB_33436 = 'shared-ui-web-33436',
  SHARED_UI_WEB_31599 = 'shared-ui-web-31599',
  SHARED_UI_WEB_30536 = 'shared-ui-web-30536',
  SHARED_UI_WEB_21664 = 'shared-ui-web-21664',
  SHARED_UI_WEB_19577 = 'shared-ui-web-19577',
  SHARED_UI_WEB_18919 = 'shared-ui-web-18919',
  SHARED_UI_WEB_18503 = 'shared-ui-web-18503',
  SHARED_UI_WEB_17571 = 'shared-ui-web-17571',
  SHARED_UI_WEB_17220 = 'shared-ui-web-17220',
  SHARED_UI_WEB_16805 = 'shared-ui-web-16805',
  SHARED_UI_WEB_15935 = 'shared-ui-web-15935',
  SHARED_UI_WEB_15745 = 'shared-ui-web-15745',
  SHARED_UI_WEB_14474 = 'shared-ui-web-14474',
  SHARED_UI_WEB_14227 = 'shared-ui-web-14227',
  SHARED_UI_WEB_12593 = 'shared-ui-web-12593',
  SHARED_UI_WEB_11332 = 'shared-ui-web-11332',
  SHARED_UI_WEB_10735 = 'shared-ui-web-10735',

  // egds-components-react
  EGDS_COMPONENTS_REACT_1898 = 'egds-components-react-1898',
  EGDS_COMPONENTS_REACT_1011 = 'egds-components-react-1011',
  EGDS_COMPONENTS_REACT_956 = 'egds-components-react-956',
  EGDS_COMPONENTS_REACT_797 = 'egds-components-react-797',
  EGDS_COMPONENTS_REACT_759 = 'egds-components-react-759',
  EGDS_COMPONENTS_REACT_735 = 'egds-components-react-735',
  EGDS_COMPONENTS_REACT_720 = 'egds-components-react-720',
  EGDS_COMPONENTS_REACT_712 = 'egds-components-react-712',

  // product-details-experience-api
  PRODUCT_DETAILS_API_3590 = 'product-details-api-3590',
  PRODUCT_DETAILS_API_3572 = 'product-details-api-3572',
  PRODUCT_DETAILS_API_3527 = 'product-details-api-3527',
  PRODUCT_DETAILS_API_3360 = 'product-details-api-3360',
  PRODUCT_DETAILS_API_3350 = 'product-details-api-3350',
  PRODUCT_DETAILS_API_3225 = 'product-details-api-3225',
  PRODUCT_DETAILS_API_3218 = 'product-details-api-3218',

  // experience-api-lodging-offers
  EXP_API_LODGING_OFFERS_10403 = 'exp-api-lodging-offers-10403',
  EXP_API_LODGING_OFFERS_10243 = 'exp-api-lodging-offers-10243',

  // experience-api-lodging-property
  EXP_API_LODGING_PROPERTY_3221 = 'exp-api-lodging-property-3221',

  // shared-graphql
  SHARED_GRAPHQL_8231 = 'shared-graphql-8231',
}

export enum TopicId {
  MANAGES_COLLECTIONS_OF_DATA_USING_LANGUAGE = 'manages-collections-of-data-using-language',
  STORES_REUSES_AND_MANIPULATES_DATA = 'stores-reuses-and-manipulates-data',
  STORES_REUSES_AND_OPERATES_ON_BASIC_DATA_TYPES = 'stores-reuses-and-operates-on-basic-data-types',
  USES_AND_MAINTAINS_LANGUAGE_OPERATORS_AND_COMMENTS = 'uses-and-maintains-language-operators-and-comments',
  APPLIES_AND_MAINTAINS_CONTROL_FLOW_STRUCTURES = 'applies-and-maintains-control-flow-structures',
  HANDLES_EXCEPTIONS_USING_LANGUAGE_CAPABILITIES = 'handles-exceptions-using-language-capabilities',
  HANDLES_USER_INTERACTION_WITH_EVENTS_HANDLERS = 'handles-user-interaction-with-events-handlers',
  INTERACTS_WITH_A_USER_INTERFACE_USING_LANGUAGE_BUILT_IN_TECHNICS = 'interacts-with-a-user-interface-using-language-built-in-technics',
  REUSES_AND_ENCAPSULATES_RELATED_DATA_AND_BEHAVIOUR = 'reuses-and-encapsulates-related-data-and-behaviour',
  USES_BUILT_IN_ITERATORS_TO_TRAVERSE_THROUGH_DIFFERENT_TYPES_OF_COLLECTIONS = 'uses-built-in-iterators-to-traverse-through-different-types-of-collections',
  ACCESSES_AND_STORES_DATA_IN_A_CLIENT_SIDE_STORAGE = 'accesses-and-stores-data-in-a-client-side-storage',
  DEFINES_MAINTAINS_AND_USES_MODULAR_STRUCTURES_FOR_CODE_NAMESPACING_AND_REUSABILITY = 'defines-maintains-and-uses-modular-structures-for-code-namespacing-and-reusability',
  IMPLEMENTS_ASYNCHRONY_AND_NON_BLOCKING_ENVIRONMENT_CONCEPTS = 'implements-asynchrony-and-non-blocking-environment-concepts',
  IMPLEMENTS_CONCURRENCY_CONCEPTS_BY_USING_LANGUAGE_CAPABILITIES = 'implements-concurrency-concepts-by-using-language-capabilities',
  MANAGES_FILES_WITH_LANGUAGE_FILESYSTEM_CAPABILITIES = 'manages-files-with-language-filesystem-capabilities',
  MANIPULATES_DATE_AND_TIME_WITH_LANGUAGE_APIS = 'manipulates-date-and-time-with-language-apis',
  SENDS_AND_RETRIEVES_DATA_THROUGH_A_NETWORK_USING_LANGUAGE_CAPABILITIES = 'sends-and-retrieves-data-through-a-network-using-language-capabilities',
  USES_LANGUAGE_APIS_FOR_MATHEMATICAL_OPERATIONS = 'uses-language-apis-for-mathematical-operations',
  VALIDATES_FINDS_AND_REPLACES_STRING_DATA_WITH_REGULAR_EXPRESSIONS = 'validates-finds-and-replaces-string-data-with-regular-expressions',
  APPLIES_METHODOLOGY_AND_BEST_PRACTICES_FOR_LANGUAGE_PERFORMANCE_OPTIMISATION = 'applies-methodology-and-best-practices-for-language-performance-optimisation',
  BUILDS_CLIENT_SERVER_APPLICATIONS_USING_NETWORK_PROTOCOLS = 'builds-client-server-applications-using-network-protocols',
  CREATES_AND_MAINTAINS_CUSTOM_USER_INTERFACE_COMPONENTS = 'creates-and-maintains-custom-user-interface-components',
  MANAGES_ADVANCED_COLLECTIONS_OF_DATA_USING_LANGUAGE = 'manages-advanced-collections-of-data-using-language',
  MANAGES_AND_IMPLEMENTS_COMPLEX_DATA_STRUCTURES = 'manages-and-implements-complex-data-structures',
  OPTIMISES_APPLICATION_PERFORMANCE_TAKING_INTO_ACCOUNT_THE_COMPLEXITY_OF_THE_ALGORITHMS = 'optimises-application-performance-taking-into-account-the-complexity-of-the-algorithms',
  SECURES_NETWORK_INTERACTION_USING_A_PROGRAMMING_LANGUAGE = 'secures-network-interaction-using-a-programming-language',
  SYNCHRONISES_CONCURRENT_OPERATIONS_BY_USING_LANGUAGE_CAPABILITIES = 'synchronises-concurrent-operations-by-using-language-capabilities',
  USES_LANGUAGE_METAPROGRAMMING_TECHNIQUES = 'uses-language-metaprogramming-techniques',
  CREATES_SUPPORTS_AND_COMPOSES_USER_INTERFACE_COMPONENTS = 'creates-supports-and-composes-user-interface-components',
  STYLING_ELEMENTS_USING_FRAMEWORK_CAPABILITY = 'styling-elements-using-framework-capability',
  USES_BUILT_IN_MECHANISM_TO_MANAGE_COMPONENT_INTERACTION = 'uses-built-in-mechanism-to-manage-component-interaction',
  USES_TECHNICS_TO_DYNAMICALLY_GENERATE_ELEMENTS = 'uses-technics-to-dynamically-generate-elements',
  APPLIES_TECHNICS_AND_USES_TECHNOLOGY_FOR_STYLING_COMPONENTS = 'applies-technics-and-uses-technology-for-styling-components',
  DISPLAYS_DATA_ON_THE_USER_INTERFACE = 'displays-data-on-the-user-interface',
  HANDLES_USER_INTERACTION_WITH_EVENT_HANDLERS_IN_FRAMEWORK = 'handles-user-interaction-with-event-handlers-in-framework',
  INTERACTS_WITH_API_AND_HANDLES_REQUEST_METADATA = 'interacts-with-api-and-handles-request-metadata',
  INTERACTS_WITH_LIFECYCLES_IN_COMPONENTS_USING_FRAMEWORK_CAPABILITY = 'interacts-with-lifecycles-in-components-using-framework-capability',
  SETS_UP_BUILDS_TESTS_AND_DEPLOYS_APPLICATION_WITH_CLI = 'sets-up-builds-tests-and-deploys-application-with-cli',
  USES_BASIC_ROUTER_CAPABILITY_FOR_BUILDING_NAVIGATION = 'uses-basic-router-capability-for-building-navigation',
  APPLIES_SECURITY_PRACTICES_AND_APPROACHES_TO_PROTECT_APPLICATION = 'applies-security-practices-and-approaches-to-protect-application',
  DEFINES_CUSTOM_EVENT_FOR_HANDLING_USER_INTERACTION = 'defines-custom-event-for-handling-user-interaction',
  HANDLES_INTERNATIONALISATION_IN_SCOPE_OF_THE_APPLICATIONS_DEVELOPMENT = 'handles-internationalisation-in-scope-of-the-applications-development',
  MANAGES_DATA_FOR_DEVELOPING_DYNAMIC_AND_HIGHLY_SCALABLE_APPLICATIONS = 'manages-data-for-developing-dynamic-and-highly-scalable-applications',
  USES_ADVANCED_ROUTER_CAPABILITY_FOR_BUILDING_NAVIGATION = 'uses-advanced-router-capability-for-building-navigation',
  USES_FORMS_FOR_USER_INPUTS_AND_INTERACTION = 'uses-forms-for-user-inputs-and-interaction',
  USES_FRAMEWORK_BUILT_IN_TOOLS_FOR_CODE_REUSABILITY = 'uses-framework-built-in-tools-for-code-reusability',
  USES_FRAMEWORK_RELATED_AND_BASIC_TOOLS_FOR_APPLICATION_S_DEBUGGING = 'uses-framework-related-and-basic-tools-for-application-s-debugging',
  APPLIES_ACCESSIBILITY_RULES_AND_GUIDELINES_FOR_BUILDING_USER_INTERFACE = 'applies-accessibility-rules-and-guidelines-for-building-user-interface',
  CREATES_AND_MAINTAINS_COMPONENT_LIBRARY = 'creates-and-maintains-component-library',
  OPTIMIZES_APPLICATION_WITH_CODE_SPLITTING_TECHNIQUES = 'optimizes-application-with-code-splitting-techniques',
  DEBUGS_APPLICATION_USING_DEBUGGING_TOOLS_AND_TECHNIQUES = 'debugs-application-using-debugging-tools-and-techniques',
  MANAGES_PROJECT_DEPENDENCIES_WITH_PACKAGE_MANAGERS = 'manages-project-dependencies-with-package-managers',
  CONVERTERS_AND_FORMATES_DATE_AND_TIME_USING_DATE_TIME_LIBRARIES = 'converters-and-formates-date-and-time-using-date-time-libraries',
  CREATES_AND_UPDATES_FILES_WITH_TOOLS_AND_LIBRARIES = 'creates-and-updates-files-with-tools-and-libraries',
  ENSURES_TYPE_INTEGRITY_IN_THE_APPLICATION = 'ensures-type-integrity-in-the-application',
  HANDLES_USER_INPUT_THROUGH_FORM_WIDGETS = 'handles-user-input-through-form-widgets',
  SANITIZES_DATA_USING_EXTRA_LIBRARIES = 'sanitizes-data-using-extra-libraries',
  SIMPLIFIES_ACCESS_TO_BROWSERS_STORAGE_USING_TOOLS_OR_LIBRARIES = 'simplifies-access-to-browsers-storage-using-tools-or-libraries',
  GENERATES_DOCUMENTATION_THROUGH_TOOLS_OR_LIBRARIES = 'generates-documentation-through-tools-or-libraries',
  HANDLES_AND_RESOLVES_NEW_VERSIONS_OF_THE_PACKAGES = 'handles-and-resolves-new-versions-of-the-packages',
  HANDLES_DIFFERENT_TYPES_OF_LOCALIZATION_AND_TEXT_PROCESSING = 'handles-different-types-of-localization-and-text-processing',
  HANDLES_FILES_UPLOAD_THROUGH_LIBRARIES = 'handles-files-upload-through-libraries',
  HANDLES_IMAGES_UPLOAD_THROUGH_TOOLS_AND_LIBRARIES = 'handles-images-upload-through-tools-and-libraries',
  HANDLES_SCROLL_DETECTION_THROUGH_TOOLS_AND_LIBRARIES = 'handles-scroll-detection-through-tools-and-libraries',
  OPTIMIZES_THE_DEVELOPMENT_PROCESS_WITH_UTILS = 'optimizes-the-development-process-with-utils',
  PROVIDES_SUPPORT_FOR_DIFFERENT_BROWSERS = 'provides-support-for-different-browsers',
  TROUBLESHOOTS_NETWORK_USING_TOOLS_AND_LIBRARIES = 'troubleshoots-network-using-tools-and-libraries',
  USES_HTTP_CLIENTS_FOR_API_COMMUNICATION = 'uses-http-clients-for-api-communication',
  USES_TOOLS_AND_LIBRARIES_FOR_IMMUTABILITY = 'uses-tools-and-libraries-for-immutability',
  VALIDATES_DATA_WITH_TOOLS_AND_LIBRARIES = 'validates-data-with-tools-and-libraries',
  CONFIGURES_BUNDLERS_FOR_APPLICATION = 'configures-bundlers-for-application',
  CREATES_CUSTOM_PLUGINS_FOR_BUNDLERS = 'creates-custom-plugins-for-bundlers',
  PROVIDES_DATA_VISUALIZATIONS_THROUGH_VISUALIZATION_TOOLS = 'provides-data-visualizations-through-visualization-tools',
  USES_LIBRARIES_FOR_LOGGING_DATA = 'uses-libraries-for-logging-data',
  ADDS_STYLING_TO_TEMPLATE_DOCUMENT = 'adds-styling-to-template-document',
  ADJUSTS_VALUES_AND_UNITS_TO_SET_THE_SIZE_OF_VARIOUS_ELEMENTS_WITH_STYLE_SHEET_LANGUAGE = 'adjusts-values-and-units-to-set-the-size-of-various-elements-with-style-sheet-language',
  HANDLES_OVERFLOWING_CONTENT_ON_A_PAGE = 'handles-overflowing-content-on-a-page',
  STYLES_ELEMENTS_USING_BASIC_STYLE_SHEET_LANGUAGE_PROPERTIES = 'styles-elements-using-basic-style-sheet-language-properties',
  USES_BASIC_BOX_MODEL_AND_HANDLES_MARGIN_COLLAPSING = 'uses-basic-box-model-and-handles-margin-collapsing',
  ALIGNS_VARIOUS_ELEMENT_POSITIONS_WITH_STYLE_SHEET_LANGUAGE = 'aligns-various-element-positions-with-style-sheet-language',
  CREATES_AND_COMPOSES_PAGES_AND_LAYOUTS_USING_STANDARD_MARKUP_LANGUAGE = 'creates-and-composes-pages-and-layouts-using-standard-markup-language',
  CREATES_FORMS_USING_A_STANDARD_MARKUP_LANGUAGE = 'creates-forms-using-a-standard-markup-language',
  CREATES_LAYOUTS_WITH_BASIC_LAYOUT_MODES_USING_STYLE_SHEET_LANGUAGE = 'creates-layouts-with-basic-layout-modes-using-style-sheet-language',
  CREATES_TABLES_WITH_A_STANDARD_MARKUP_LANGUAGE = 'creates-tables-with-a-standard-markup-language',
  DEBUGS_MARKUPS_AND_STYLES = 'debugs-markups-and-styles',
  STYLES_ELEMENTS_WITH_VARIOUS_STYLE_SHEET_LANGUAGE_SELECTORS = 'styles-elements-with-various-style-sheet-language-selectors',
  STYLES_TEXT_USING_BASIC_STYLE_SHEET_LANGUAGE_RULES = 'styles-text-using-basic-style-sheet-language-rules',
  ANIMATES_USER_INTERFACE_ELEMENTS_USING_STYLE_SHEET_LANGUAGE = 'animates-user-interface-elements-using-style-sheet-language',
  APPLIES_STANDARDISED_METHODOLOGIES_WHILE_USING_STYLE_SHEET_LANGUAGE = 'applies-standardised-methodologies-while-using-style-sheet-language',
  CREATES_LAYOUTS_WITH_ADVANCED_LAYOUT_MODES_USING_STYLE_SHEET_LANGUAGE = 'creates-layouts-with-advanced-layout-modes-using-style-sheet-language',
  CREATES_RESPONSIVE_LAYOUTS_WITH_ADAPTIVE_TECHNICS = 'creates-responsive-layouts-with-adaptive-technics',
  EMBEDS_CONTENT_FROM_ANOTHER_SOURCE_INTO_A_WEBPAGE = 'embeds-content-from-another-source-into-a-webpage',
  STYLES_USER_INTERFACE_USING_PREPROCESSORS_OR_SCRIPTING_SOLUTIONS = 'styles-user-interface-using-preprocessors-or-scripting-solutions',
  TRANSFORMS_ELEMENTS_USING_STYLE_SHEETS = 'transforms-elements-using-style-sheets',
  CREATES_ACCESSIBLE_WEB_PAGES = 'creates-accessible-web-pages',
  CREATES_WEB_PAGES_FOR_VARIOUS_DEVICE_TYPES = 'creates-web-pages-for-various-device-types',
  OPTIMISES_APPLICATIONS_FOR_SEARCH_ENGINES = 'optimises-applications-for-search-engines',
  OPTIMISES_PAGE_PERFORMANCE = 'optimises-page-performance',
  APPLIES_COMMUNITY_RECOMMENDED_PRACTICE_AND_METHODOLOGIES_TO_AUTOMATED_TESTS = 'applies-community-recommended-practice-and-methodologies-to-automated-tests',
  STRUCTURES_TESTS_USING_FRAMEWORK_CAPABILITIES = 'structures-tests-using-framework-capabilities',
  USES_DUMMY_DATA_FOR_TESTING = 'uses-dummy-data-for-testing',
  USES_MATCHERS_FOR_TESTING_EXPECTED_RESULT = 'uses-matchers-for-testing-expected-result',
  USES_UNIT_TESTS_TECHNIQUES = 'uses-unit-tests-techniques',
  TESTS_ASYNC_CODE_USING_FRAMEWORK_CAPABILITIES = 'tests-async-code-using-framework-capabilities',
  USES_FAKE_OBJECTS_TO_DECOUPLE_FROM_DEPENDENCIES = 'uses-fake-objects-to-decouple-from-dependencies',
  USES_INTEGRATION_TEST_APPROACHES_STRATEGIES_AND_METHODOLOGIES = 'uses-integration-test-approaches-strategies-and-methodologies',
  USES_TECHNIQUES_AND_METHODOLOGY_FOR_ACCESSIBILITY_TESTING = 'uses-techniques-and-methodology-for-accessibility-testing',
  CONFIGURES_AND_MAINTAINS_CODE_COVERAGE_REPORTS = 'configures-and-maintains-code-coverage-reports',
  CONFIGURES_TEST_FRAMEWORK_FOR_TESTS_EXECUTION = 'configures-test-framework-for-tests-execution',
  CREATES_AND_ORGANISES_END_TO_END_TESTS = 'creates-and-organises-end-to-end-tests',
  CREATES_COMPONENTS_AND_MODULES_USING_BASIC_DESIGN_TECHNIQUES = 'creates-components-and-modules-using-basic-design-techniques',
  CREATES_REUSABLE_STRUCTURES_BY_APPLYING_DESIGN_STRATEGIES_AND_METHODOLOGIES = 'creates-reusable-structures-by-applying-design-strategies-and-methodologies',
  IMPLEMENTS_SOLUTIONS_BASED_ON_DIFFERENT_REQUIREMENT_TYPES = 'implements-solutions-based-on-different-requirement-types',
  COLLECTS_DATA_USING_REQUIREMENTS_ELICITATION_TECHNIQUES_AND_METHODOLOGIES = 'collects-data-using-requirements-elicitation-techniques-and-methodologies',
  REFACTORS_AND_RESTRUCTURES_SOFTWARE_COMPONENTS_AND_MODULES_USING_COMMUNITY_RECOMMENDED_PRACTICES_AND_METHODOLOGIES = 'refactors-and-restructures-software-components-and-modules-using-community-recommended-practices-and-methodologies',
  USES_DESIGN_PATTERNS_TO_CREATE_NEW_STRUCTURES_BASED_ON_REQUIREMENTS = 'uses-design-patterns-to-create-new-structures-based-on-requirements',
  USES_DIFFERENT_REQUIREMENT_SOURCES_FOR_SOLUTION_IMPLEMENTATION = 'uses-different-requirement-sources-for-solution-implementation',
  DISTRIBUTES_RESPONSIBILITY_BETWEEN_STRUCTURES_USING_DESIGN_PATTERNS = 'distributes-responsibility-between-structures-using-design-patterns',
  ENSURES_EFFICIENT_AND_FLEXIBLE_COMPOSITION_OF_STRUCTURES_WITH_DESIGN_PATTERNS = 'ensures-efficient-and-flexible-composition-of-structures-with-design-patterns',
  EVALUATES_AND_MODIFIES_SOFTWARE_DESIGN_TO_ENSURE_SOFTWARE_QUALITY = 'evaluates-and-modifies-software-design-to-ensure-software-quality',
  USES_METHODOLOGIES_AND_TECHNICS_TO_DOCUMENT_DESIGN = 'uses-methodologies-and-technics-to-document-design',
  USES_MODELLING_TECHNIQUES_FOR_REQUIREMENTS_ANALYSIS = 'uses-modelling-techniques-for-requirements-analysis',
  VALIDATES_REQUIREMENTS_USING_VARIOUS_METHODOLOGIES_AND_TECHNICS = 'validates-requirements-using-various-methodologies-and-technics',
  MANAGES_ENVIRONMENTS_USING_BUILT_IN_OPERATING_SYSTEM_TOOLS = 'manages-environments-using-built-in-operating-system-tools',
  USES_VERSION_CONTROL_TOOLS_FOR_DEVELOPMENT = 'uses-version-control-tools-for-development',
  CONFIGURES_AND_MAINTAINS_DEVELOPMENT_ENVIRONMENT_AND_ECOSYSTEM = 'configures-and-maintains-development-environment-and-ecosystem',
  CONTAINERISE_APPLICATION_FOR_THE_PURPOSE_OF_SIMPLIFIED_DISTRIBUTION = 'containerise-application-for-the-purpose-of-simplified-distribution',
  DISTRIBUTES_WORK_USING_VERSION_CONTROL_TOOLS = 'distributes-work-using-version-control-tools',
  MAINTAINS_CODE_QUALITY_OF_THE_APPLICATION = 'maintains-code-quality-of-the-application',
  MANAGES_AND_MAINTAINS_THE_CONDITION_OF_THE_APPLICATION_S_DEPENDENCIES = 'manages-and-maintains-the-condition-of-the-application-s-dependencies',
  PREVENTS_AND_FIXES_THREATS_AND_VULNERABILITIES_BY_MAINTAINING_CODE_SECURITY = 'prevents-and-fixes-threats-and-vulnerabilities-by-maintaining-code-security',
  CONFIGURES_CONTRIBUTION_WORKFLOW_USING_VERSION_CONTROL_TOOLS = 'configures-contribution-workflow-using-version-control-tools',
  CONFIGURES_INTEGRATION_PROCESS_USING_CI_TOOLS = 'configures-integration-process-using-ci-tools',
  CONFIGURES_THE_BUILD_PROCESS_TO_COMPILE_READY_TO_USE_APPLICATIONS_FROM_SOURCE_CODE = 'configures-the-build-process-to-compile-ready-to-use-applications-from-source-code',
  CONTROLS_CODE_QUALITY_WITH_MEASUREMENT_TOOLS = 'controls-code-quality-with-measurement-tools',
  CREATES_ECOSYSTEM_FOR_APPLICATION_STATE_MONITORING = 'creates-ecosystem-for-application-state-monitoring',
  HANDLES_ENVIRONMENT_VARIABLES_AND_SECRETS = 'handles-environment-variables-and-secrets',
  SET_UPS_CODE_REVIEW_PROCESS_TO_ACHIEVE_THE_QUALITY_OF_THE_APPLICATION = 'set-ups-code-review-process-to-achieve-the-quality-of-the-application',
  ACCESSES_CLOUD_ENVIRONMENT_FOR_DEVELOPMENT_AND_DEBUGGING = 'accesses-cloud-environment-for-development-and-debugging',
  MANAGES_MESSAGE_QUEUING_IN_A_CLOUD = 'manages-message-queuing-in-a-cloud',
  STORES_AND_SYNCS_APP_DATA_IN_A_CLOUD = 'stores-and-syncs-app-data-in-a-cloud',
  STORES_DATA_IN_A_CLOUD_DATABASE = 'stores-data-in-a-cloud-database',
  APPLIES_SOFTWARE_PROCESS_TO_IMPROVE_PRODUCT_QUALITY_AND_ENSURE_EFFICIENT_WORKFLOW = 'applies-software-process-to-improve-product-quality-and-ensure-efficient-workflow',
  USES_PROJECT_MANAGEMENT_TOOLS_WITHIN_SELECTED_SOFTWARE_DEVELOPMENT_METHODOLOGIES = 'uses-project-management-tools-within-selected-software-development-methodologies',
  ADJUSTS_AN_ESTIMATION_PROCESS_USING_THE_DATA_GATHERED_FROM_THE_REQUIREMENTS_ELICITATION = 'adjusts-an-estimation-process-using-the-data-gathered-from-the-requirements-elicitation',
  CONTRIBUTES_TO_A_RISK_MANAGEMENT_PROCESS_TO_DETECT_AND_MITIGATE_POTENTIAL_ISSUES = 'contributes-to-a-risk-management-process-to-detect-and-mitigate-potential-issues',
  CONTRIBUTES_TO_A_STANDARDS_SELECTION_PROCESS = 'contributes-to-a-standards-selection-process',
  CREATES_AND_MAINTAINS_DOCUMENTATION_FOR_SOFTWARE_REQUIREMENTS_SPECIFICATION = 'creates-and-maintains-documentation-for-software-requirements-specification',
  ESTABLISHES_OR_REFINES_A_TECHNICAL_DEBT_POLICY = 'establishes-or-refines-a-technical-debt-policy',
  ESTABLISHES_OR_REFINES_REQUIREMENTS_ELICITATION_PROCESS = 'establishes-or-refines-requirements-elicitation-process',
  IMPROVES_A_QUALITY_MANAGEMENT_PROCESS_BY_CONTRIBUTING_TO_A_QUALITY_DOCUMENTATION = 'improves-a-quality-management-process-by-contributing-to-a-quality-documentation',
  IMPROVES_APPLICATION_DELIVERY_BY_CONTRIBUTING_TO_A_RELEASE_PROCESS = 'improves-application-delivery-by-contributing-to-a-release-process',
  ESTIMATES_TASKS_BASED_ON_REQUIREMENTS = 'estimates-tasks-based-on-requirements',
  MANAGES_TECHNICAL_DEBT_BASED_ON_PRIORITIES = 'manages-technical-debt-based-on-priorities',
  IMPROVES_CODE_REVIEW_PROCESS_TO_ENHANCE_EFFICIENCY_AND_QUALITY = 'improves-code-review-process-to-enhance-efficiency-and-quality',
  MANAGES_WORKLOAD_BASED_ON_REQUIREMENTS = 'manages-workload-based-on-requirements',
  PASSES_ONBOARDING_INTO_ENGINEERING_AND_TECHNOLOGY_EXPERTISE_INCLUDING_SPECIALISATION_OR_PRACTICE = 'passes-onboarding-into-engineering-and-technology-expertise-including-specialisation-or-practice',
  PASSES_PERFORMANCE_REVIEW_ACCORDING_TO_THE_PROCESS_DEFINITION_AND_REQUIREMENTS = 'passes-performance-review-according-to-the-process-definition-and-requirements',
  CONTRIBUTES_TO_DEVELOPMENT_OF_ENGINEERING_AND_TECHNOLOGY_JOBS_AND_SKILLS_STANDARDS = 'contributes-to-development-of-engineering-and-technology-jobs-and-skills-standards',
  CONTRIBUTES_TO_OPEN_SOURCE_PROJECT_DEVELOPMENT = 'contributes-to-open-source-project-development',
  CONTRIBUTES_TO_OPEN_TECH_PROJECT_DEVELOPMENT = 'contributes-to-open-tech-project-development',
  DEVELOPS_ASSOCIATES_OR_CANDIDATES_WITHIN_ENGINEERING_AND_TECHNOLOGY_SPECIALISATION_PROFILE = 'develops-associates-or-candidates-within-engineering-and-technology-specialisation-profile',
  CONDUCTS_EVALUATIONS_IN_JOB_INTERVIEW_EVENTS_WITHIN_THE_CURRENT_COMPETENCY_PROFILE_ON_THE_PROJECT_AND_COMPANY_SCALE = 'conducts-evaluations-in-job-interview-events-within-the-current-competency-profile-on-the-project-and-company-scale',
  CONDUCTS_EVALUATIONS_IN_PERFORMANCE_REVIEW_EVENTS_WITHIN_THE_CURRENT_COMPETENCY_PROFILE_ON_THE_PROJECT_AND_COMPANY_SCALE = 'conducts-evaluations-in-performance-review-events-within-the-current-competency-profile-on-the-project-and-company-scale',
  CONTRIBUTES_TO_DEVELOPMENT_OF_ENGINEERING_AND_TECHNOLOGY_LEARNING_SOLUTIONS_FOR_PEOPLE_PROFESSIONAL_GROWTH = 'contributes-to-development-of-engineering-and-technology-learning-solutions-for-people-professional-growth',
  CONTRIBUTES_TO_DEVELOPMENT_OF_ENGINEERING_AND_TECHNOLOGY_STANDARDS_FOR_PROCESSES_AND_SOLUTIONS_IMPLEMENTATION = 'contributes-to-development-of-engineering-and-technology-standards-for-processes-and-solutions-implementation',
  SHARES_PROFESSIONAL_EXPERIENCE_IN_CONTEXT_OF_THE_CURRENT_COMPETENCY_PROFILE_AT_ANY_ASSOCIATES_GATHERING_EVENT_ON_A_PROJECT_OR_COMPANY_SCALE = 'shares-professional-experience-in-context-of-the-current-competency-profile-at-any-associates-gathering-event-on-a-project-or-company-scale',
  PASS_ONBOARDING_AND_EDUCATIONAL_COURSES_OF_GENERATIVE_AI_APPLICATION_AND_USAGE_WITHIN_THE_ROLE_ON_THE_PROJECT_AND_COMPANY = 'pass-onboarding-and-educational-courses-of-generative-ai-application-and-usage-within-the-role-on-the-project-and-company',
  PASS_TRAINING_OF_SECURE_AND_ETHICAL_GENERATIVE_AI_APPLICATION_WITHIN_THE_PROJECT_AND_COMPANY = 'pass-training-of-secure-and-ethical-generative-ai-application-within-the-project-and-company',
  USE_DEFAULT_FUNCTIONALITY_COMMANDS_AND_PROMPTS_SUGGESTED_BY_GENERATIVE_AI_TOOLS_TO_CREATE_OUTCOMES = 'use-default-functionality-commands-and-prompts-suggested-by-generative-ai-tools-to-create-outcomes',
  CONFIGURE_ADOPTED_GENERATIVE_AI_TOOLS_TO_WORK_ON_DAILY_ACTIVITIES_AND_TASKS = 'configure-adopted-generative-ai-tools-to-work-on-daily-activities-and-tasks',
  USES_GENERATIVE_AI_CHAT_FUNCTIONALITY_TO_GAIN_PROJECT_AND_SPECIALIZATION_KNOWLEDGE_AND_SKILLS = 'uses-generative-ai-chat-functionality-to-gain-project-and-specialization-knowledge-and-skills',
  USE_GENERATIVE_AI_TOOLS_ON_DAILY_BASIS_INTEGRATE_AI_FUNCTIONALITIES_IN_DAILY_PROCESSES_AND_TASKS_TO_CREATE_OUTCOMES = 'use-generative-ai-tools-on-daily-basis-integrate-ai-functionalities-in-daily-processes-and-tasks-to-create-outcomes',
  APPLY_ADVANCED_PROMPTING_TECHNIQUES_TO_INCREASE_GENERATIVE_AI_EFFICIENCY_FOR_TASKS_WITH_COMPLEX_CONTEXT_TO_CREATE_OUTCOMES = 'apply-advanced-prompting-techniques-to-increase-generative-ai-efficiency-for-tasks-with-complex-context-to-create-outcomes',
  APPLY_GENERATIVE_AI_PROMPTING_TEMPLATES_DEFINED_WITHIN_THE_PROJECT_TO_CREATE_OUTCOMES = 'apply-generative-ai-prompting-templates-defined-within-the-project-to-create-outcomes',
  ACTIVELY_ENGAGE_WITH_THE_GEN_AI_COMMUNITY_BY_PARTICIPATING_IN_EVENTS_AND_COURSES = 'actively-engage-with-the-gen-ai-community-by-participating-in-events-and-courses',
  REFINE_AND_TUNE_PROMPTS_FOR_SPECIFIC_TASKS_TO_IMPROVE_ACCURACY_AND_RELEVANCE_CREATE_PROMPTING_FLOWS_HAVING_RIGHT_DECOMPOSITION_TECHNIQUES_TO_RECEIVE_RIGHT_ANSWERS_FROM_MODEL = 'refine-and-tune-prompts-for-specific-tasks-to-improve-accuracy-and-relevance-create-prompting-flows-having-right-decomposition-techniques-to-receive-right-answers-from-model',
  APPLY_ADVANCED_GENERATIVE_AI_PROMPTING_STRATEGIES_TO_COMPLEX_TASKS_TO_CREATE_OUTCOMES = 'apply-advanced-generative-ai-prompting-strategies-to-complex-tasks-to-create-outcomes',
  DESIGN_NEW_PROMPTING_TEMPLATES_FOR_TASKS_WITHIN_THE_PROJECT_TO_CREATE_OUTCOMES = 'design-new-prompting-templates-for-tasks-within-the-project-to-create-outcomes',
  DISCOVER_AND_DOCUMENT_NEW_GENERATIVE_AI_USE_CASES_WITHIN_THE_SPECIALIZATION = 'discover-and-document-new-generative-ai-use-cases-within-the-specialization',
  CONTRIBUTE_TO_GENERATIVE_AI_EXPERTISE_DEVELOPMENT_WITHIN_THE_COMPANY_TO_EXTEND_CORPORATE_KNOWLEDGE_BASE = 'contribute-to-generative-ai-expertise-development-within-the-company-to-extend-corporate-knowledge-base',
}

export interface Repo {
  id: RepoId
  name: string
  url: string
}

export interface PullRequest {
  id: PullRequestId
  repoId: RepoId
  title: string
  url: string
}

export type PrTopicMappings = {
  [K in PullRequestId]: { topicId: TopicId; contribution: string }[]
}

export interface TopicPr extends PullRequest {
  contribution: string
  repoName: string
  parentFeature?: ParentFeature
}

export interface Topic {
  id: TopicId
  name: string
  tags: string[]
  prs: TopicPr[]
}
